### ISSUE TITLE
Make this a TC39 proposal

### ISSUE THREAD

**Issue by ColinEberhardt** [rbuckton/reflect-metadata#96] opened 2018-10-22 10:34 UTC
I was looking at using Decorators to create some metadata-driven functionality, which is how I came upon this project.

I'm surprised that this isn't on the list of TC39 proposals:

https://github.com/tc39/proposals

Especially as it is being used by Angular, which means it is gaining some significant mainstream usage. Is this project / proposal still active?

**Comment by jkrems** [comment] 2018-10-29 14:11
> Especially as it is being used by Angular, [...]

@ColinEberhardt Angular isn't using JS decorators as they are proposed in the standards process. They are using a custom take on an early stage 0 draft of the feature. Real decorators have changed since then. For Angular the more interesting question is the Typescript feature and how it will evolve if and when Typescript implements JS decorators.

**Comment by nicojs** [comment] 2018-12-17 07:11
Yes, make this a TC39 proposal. The readme links to the [detailed proposal](https://rbuckton.github.io/reflect-metadata), however it is nowhere to be seen other than there. What happened here?

I'm interested in using Reflect.metadata (for dep injection in node modules), but only if I can see a future in it.

**Comment by glen-84** [comment] 2019-12-13 10:57
Duplicate of #9.

**Closed** 2023-12-09 02:13 UTC
Labels: Duplicate
